
"""

Q1: How Do You Handle Exceptions With Try/Except/Finally In Python?

ANS:

==> try : This block will test the excepted error to occur.

==> except : Here you can handle the error.

==> else : If there is no exception then this block will be exception is generated or not.

==> finally : finally block aiways gets executed either exception is generated or not.

"""